// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-y6y0aP5cJBcvLEEjmpvUnOb5jSVIcw',
    appId: '1:686039242579:web:d261eed870dd27f210f3a6',
    messagingSenderId: '686039242579',
    projectId: 'chat-app-65599',
    authDomain: 'chat-app-65599.firebaseapp.com',
    storageBucket: 'chat-app-65599.appspot.com',
    measurementId: 'G-3F0PWV0NVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsc5anNfat7HXhaPes7G5pynOUj6qt-rI',
    appId: '1:686039242579:android:685a153aff6bd4d210f3a6',
    messagingSenderId: '686039242579',
    projectId: 'chat-app-65599',
    storageBucket: 'chat-app-65599.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHSQlvW8uvV1mE_AcrcC3IBgWa434xo4',
    appId: '1:686039242579:ios:ba8e10174af3b55410f3a6',
    messagingSenderId: '686039242579',
    projectId: 'chat-app-65599',
    storageBucket: 'chat-app-65599.appspot.com',
    iosClientId: '686039242579-fe07lmecf9vnr57ejk3v93nouvbusajm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
